### ISSUE TITLE
Error on new Intesis install

### ISSUE THREAD

**Issue by phiebs** [jnimmo/hass-intesishome#11]
Tried adding and only pulled in one device, changed the update to "False" as per other issues, now all devices are being pulled in but getting this error and unavailable devices:

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:359
Integration: Climate (documentation, issues)
First occurred: 23:36:52 (1 occurrences)
Last logged: 23:36:52

Error while setting up intesishome platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/intesishome/climate.py", line 113, in async_setup_entry
    controller = hass.data[DOMAIN]["controller"].pop(config_entry.unique_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'intesishome_hass'

**Comment by kaaspad** [comment]
getting the exact same error. All devices are showing but are unavailable. I reverted to the local integration which works fine, just there is a really long delay between the frontend and something actually happening (like a few seconds). Would be great if we could figure out what the issue is here. Maybe something changed on the intesis cloud side.
