### ISSUE TITLE
Climate device not working

### ISSUE THREAD

**Issue by zjuanma** [jnimmo/hass-intesishome#13]
I have a IntesisHome device (Climate AC). In HA I can see the entity but it is disable.

Log in IntesisHome API is valid and it get the device from the API.

HomeAssistant version 2024.4.4

```

2024-06-01 14:38:28.737 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.intesishome.climate.IntesisAC'>) implements HVACMode(s): heat_cool, heat, dry, fan_only, cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'intesishome' custom integration
2024-06-01 14:38:28.739 DEBUG (MainThread) [custom_components.intesishome.climate] Added climate device with state: {'name': 'Home', 'widgets': [15, 3, 5, 7, 9, 13, 52, 53, 54], 'model': 81, 'power': 'off', 'mode': 'cool', 'fan_speed': 2, 'vvane': 'auto/stop', 'setpoint': 270, 'temperature': 255, 'remote_controller_lock': 0, 'working_hours': 210, 'alarm_status': 0, 'error_code': 0, 'setpoint_min': 160, 'setpoint_max': 320, 'config_mode_map': 31, 'runtime_mode_restrictions': 0, 'config_vertical_vanes': 0, 'config_quiet': 0, 'config_confirm_off': 0, 'config_fan_map': {1: 'low', 2: 'medium', 3: 'high'}, 'mainenance_w_reset': 0, 'mainenance_wo_reset': 0, 'filter_clean': 0, 'filter_due_hours': 0, 'uid_185': 0, 'uid_186': 0, 'unknown_uid_187': 0, 'unknown_uid_188': 0, 'unknown_uid_189': 0, 'unknown_uid_190': 0, 'unknown_uid_193': 0, 'unknown_uid_195': 1, 'unknown_uid_197': 0, 'unknown_uid_1098': 0, 'external_led': 'on', 'internal_led': 'off', 'internal_temperature_offset': 0, 'temp_limitation': 'off', 'cool_temperature_min': 240, 'cool_temperature_max': 280, 'heat_temperature_min': 230, 'unknown_uid_50008': 1, 'unknown_uid_50010': 4, 'unknown_uid_50100': 0, 'rssi': 190}
```

**Comment by JonLaliberte** [comment]
Same issue here.

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:729
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 11:32:55 AM (1 occurrences)
Last logged: 11:32:55 AM

intesishome: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 729, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/config/custom_components/intesishome/climate.py", line 373, in async_update
    self._current_temp = self._controller.get_temperature(self._device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyintesishome/intesisbase.py", line 404, in get_temperature
    temperature = self.get_device_property(device_id, "temperature")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyintesishome/intesisbase.py", line 194, in get_device_property
    return self._devices[str(device_id)].get(property_name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'X'
```
