### ISSUE TITLE
Won't add intesishome_local

### ISSUE THREAD

**Issue by 11sas11** [jnimmo/hass-intesishome#5]
Sorry, no logs at this stage, but when I go to add the local version it just gives me "An unknown error occurs".  I have double checked the IP address, and using the correct user/pwd - the cloud integration goes straight through, no problems.

Image from the app.  (sorry about the colour scheme)

![image](https://user-images.githubusercontent.com/48985019/208417222-8aa9c28f-95ad-4322-b026-00c92f5cc9d9.png)

Any ideas?

**Comment by ldsmovil** [comment]
Local intesishome works perfect. I have replaced old integration with this new one. Changing cloud for local management, perfect at the moment.

**Comment by addinsella** [comment]
I have the same problem; Home Assistant provides the following log entry:
This error originated from a custom integration.

Logger: custom_components.intesishome.config_flow
Source: custom_components/intesishome/config_flow.py:128
Integration: intesishome
First occurred: 21:03:49 (2 occurrences)
Last logged: 21:18:45

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.8.159', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/intesishome/config_flow.py", line 128, in async_step_details
    await controller.poll_status()
  File "/usr/local/lib/python3.11/site-packages/pyintesishome/intesishomelocal.py", line 198, in poll_status
    await self._authenticate()
  File "/usr/local/lib/python3.11/site-packages/pyintesishome/intesishomelocal.py", line 86, in _authenticate
    async with self._web_session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.8.159:80 ssl:default [Connect call failed ('192.168.8.159', 80)]

**Comment by jnimmo** [comment]
Sorry the error isn't being handled nicely, but it looks like Home Assistant just can't connect to the device on that port, validate from VSCode on the device that you can curl a page or similar.
